#!/usr/bin/env bash
set -e

# Install coursier
curl -fLo cs https://github.com/coursier/coursier/releases/download/v2.0.3/cs-x86_64-pc-linux
chmod +x cs

# Install Almond for Scala 2.13
./cs launch almond --scala 2.13.3 -- --install
